# Generated by Django 2.0.7 on 2019-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0002_pioneer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldservicereport',
            options={'verbose_name': 'Field Service Report', 'verbose_name_plural': 'Field Service Reports'},
        ),
        migrations.AlterModelOptions(
            name='pioneer',
            options={'verbose_name': 'Pioneer', 'verbose_name_plural': 'Pioneers'},
        ),
        migrations.AlterField(
            model_name='fieldservicereport',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='tp',
            field=models.CharField(choices=[('a', 'Auxiliary Pioneer'), ('r', 'Regular Pioneer')], max_length=1, verbose_name='Type'),
        ),
    ]
