# Generated by Django 2.0.7 on 2019-03-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0005_auto_20190320_1335'),
        ('users', '0002_auto_20190320_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='congregations',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='congregations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='congregations.Congregation', verbose_name='Congregation'),
        ),
    ]
