# Generated by Django 2.0.7 on 2019-03-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190320_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='congregations',
            new_name='congregation',
        ),
    ]
