# Generated by Django 2.0.7 on 2019-04-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190320_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
