# Generated by Django 2.0.7 on 2020-03-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0015_auto_20191210_1511'),
        ('users', '0005_auto_20190412_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='congregations.Publisher', verbose_name='Publisher'),
        ),
    ]
