# Generated by Django 2.0.7 on 2019-04-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congregations', '0009_auto_20190412_1717'),
        ('financial', '0004_auto_20190416_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='congregation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='congregations.Congregation', verbose_name='Congregation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
