# Generated by Django 2.0.7 on 2019-04-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_remove_transactioncategory_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='financial.TransactionCategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
