# Generated by Django 2.0.7 on 2019-06-13 12:26

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import financial.models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0011_auto_20190503_1027'),
        ('financial', '0009_auto_20190503_1027'),
    ]

    operations = [

        migrations.AlterField(
            model_name='transaction',
            name='tc',
            field=models.CharField(blank=True, choices=[('C', 'Congregation'), ('O', 'World Wide Work'), ('D', 'Expense'), ('F', 'Construction of the Subsidiary')], max_length=1, verbose_name='Transaction Code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='td',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out'), ('OI', 'Out - In')], max_length=2, verbose_name='Transaction Direction'),
        ),
    ]
