# Generated by Django 2.0.7 on 2019-06-13 12:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import financial.models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0011_auto_20190503_1027'),
        ('financial', '0010_auto_20190613_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('carried_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carried Balance')),
                ('final_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Final Balance')),
                ('transactions', djongo.models.fields.ArrayModelField(model_container=financial.models.TransactionContent)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregations.Congregation', verbose_name='Congregation')),
            ],
            options={
                'verbose_name': 'Monthly Summary',
                'verbose_name_plural': 'Monthly Summaries',
                'ordering': ['date'],
            },
        ),
    ]
