# Generated by Django 2.0.7 on 2019-06-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_monthlysummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlysummary',
            options={'ordering': ['-date'], 'verbose_name': 'Monthly Summary', 'verbose_name_plural': 'Monthly Summaries'},
        ),
    ]
