# Generated by Django 2.0.7 on 2019-07-16 19:55

from django.db import migrations
import djongo.models.fields
from django.db.models import DecimalField


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_auto_20190630_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Value'),
        ),
    ]
