# Generated by Django 2.0.7 on 2019-10-01 19:54

from django.db import migrations, models
import djongo.models.fields
import financial.models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_auto_20190716_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sub_transactions',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=financial.models.SubTransaction),
            preserve_default=False,
        ),
    ]
