# Generated by Django 2.0.7 on 2019-12-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_auto_20191001_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tc',
            field=models.CharField(blank=True, choices=[('C', 'Congregation'), ('CE', 'Congregation (Electronic)'), ('O', 'World Wide Work'), ('D', 'Account Deposit'), ('G', 'Expense'), ('F', 'Construction of the Subsidiary'), ('J', 'Interest'), ('OE', 'Specific objective')], max_length=1, verbose_name='Transaction Code'),
        ),
    ]
