# Generated by Django 2.0.7 on 2019-03-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0006_auto_20190320_1423'),
        ('meetings', '0002_meetingaudience'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingaudience',
            name='congregation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='congregations.Congregation', verbose_name='Congregation'),
            preserve_default=False,
        ),
    ]
