# Generated by Django 2.0.7 on 2019-03-20 19:04

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingaudience_congregation'),
    ]

    operations = [

    ]
