# Generated by Django 2.0.7 on 2019-03-20 19:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20190320_1604'),
    ]

    operations = [

        migrations.AlterField(
            model_name='meetingaudience',
            name='other',
            field=models.TextField(blank=True, verbose_name='Other'),
        ),
    ]
