# Generated by Django 2.0.7 on 2019-03-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20190320_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingaudience',
            name='absences',
        ),
    ]
