# Generated by Django 2.0.7 on 2019-04-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_meetingaudience_absences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date'], 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='meetingaudience',
            options={'ordering': ['date'], 'verbose_name': 'Meeting Audience', 'verbose_name_plural': 'Meetings Audience'},
        ),
    ]
