# Generated by Django 2.0.7 on 2019-07-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0013_auto_20190716_0920'),
        ('meetings', '0008_auto_20190412_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('theme', models.CharField(blank=True, max_length=200, null=True, verbose_name='Theme')),
                ('congregation_dest', models.CharField(blank=True, max_length=200, null=True, verbose_name='Congregation Destination')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregations.Congregation', verbose_name='Congregation')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='congregations.Publisher', verbose_name='Speaker')),
            ],
            options={
                'verbose_name': 'Speaker Out',
                'verbose_name_plural': 'Speakers Out',
                'ordering': ['date'],
            },
        ),
    ]
