# Generated by Django 2.0.7 on 2019-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_speakerout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Theme')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('last_update', models.CharField(max_length=20, verbose_name='Last Update')),
            ],
        ),
    ]
