# Generated by Django 2.0.7 on 2019-07-16 13:06

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0013_auto_20190716_0920'),
        ('meetings', '0010_speech'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', djongo.models.fields.JSONField(
                    default=[], verbose_name='Dates')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='congregations.Congregation', verbose_name='Congregation')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='meetings.Speech', verbose_name='Speech')),
            ],
        ),
    ]
