# Generated by Django 2.0.7 on 2019-07-16 21:42

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_countspeech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countspeech',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meetingaudience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='speakerout',
            name='id',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='id',
        ),
        migrations.AddField(
            model_name='countspeech',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingaudience',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speakerout',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
