# Generated by Django 2.0.7 on 2019-12-10 18:11

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0015_auto_20191210_1511'),
        ('meetings', '0012_auto_20190716_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='designations',
            name='attendants',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations_attendants', to='congregations.Publisher', verbose_name='Attendants'),
        ),
        migrations.AddField(
            model_name='designations',
            name='mic_passers',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations_mic_passers', to='congregations.Publisher', verbose_name='Mic Passers'),
        ),
    ]
