# Generated by Django 2.0.7 on 2019-03-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0002_auto_20190320_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='is_active',
        ),
    ]
