# Generated by Django 2.0.7 on 2019-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0005_auto_20190320_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
