# Generated by Django 2.0.7 on 2019-03-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0006_auto_20190320_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='is_active',
        ),
    ]
