# Generated by Django 2.0.7 on 2019-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0007_remove_publisher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
