# Generated by Django 2.0.7 on 2019-04-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0008_publisher_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregation',
            options={'verbose_name': 'Congregation', 'verbose_name_plural': 'Congregations'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('full_name',), 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
    ]
