# Generated by Django 2.0.7 on 2019-04-17 12:28

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0009_auto_20190412_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongregationRole',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('account_servant', 'Account Servant'), ('secretary', 'Secretary'), ('coordinator', 'Coordinator'), ('ss', 'Superintendent of Service')], max_length=80)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregations.Congregation', verbose_name='Congregation')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregations.Publisher', verbose_name='Publisher')),
            ],
        ),
    ]
