# Generated by Django 2.0.7 on 2019-05-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0010_congregationrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregationrole',
            name='role',
            field=models.CharField(choices=[('account_servant', 'Account Servant'), ('secretary', 'Secretary'), ('coordinator', 'Coordinator'), ('ss', 'Superintendent of Service')], max_length=80, verbose_name='Role'),
        ),
    ]
