# Generated by Django 2.0.7 on 2019-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0011_auto_20190503_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='n_rooms',
            field=models.IntegerField(default=1, verbose_name='Number of Rooms'),
        ),
    ]
