# Generated by Django 2.0.7 on 2019-07-16 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0012_congregation_n_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='n_rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Number of Rooms'),
        ),
    ]
