# Generated by Django 2.0.7 on 2019-12-10 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0013_auto_20190716_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='n_attendants',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Number of Attendant'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='n_mic_passers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Number of Mic Passers'),
        ),
    ]
